../rtl/ppc_dcache_pkg.sv
../rtl/ppc_ram_sdp_be.sv
../rtl/ppc_dcache.sv
../rtl/ppc_dcache_slot.sv
../rtl/ppc_bus60x_cache_master.sv
../rtl/ppc_bus60x_snoop.sv
../rtl/ppc_bus60x_direct_store.sv
../rtl/ppc_bus60x_dbw32.sv
../rtl/ppc_biu.sv
../rtl/ppc_core_bat_cached_bus60x.sv
../rtl/ppc_bus_clock_enable.sv
