// Opt-in BAT/page translation composition with the existing scalar 60x bus.
// All physical transactions use that adapter's fixed cache-inhibited policy:
// CI_N=0, WT_N=1, GBL_N=1, CSE=00, one outstanding scalar owner. BAT/TLB
// WIMG is metadata here; no coherent cache or attribute mapping is implied.
// Instruction TEA is a sticky transport stop; the translation owner can
// remain pending/busy until reset because the arbiter consumes that error.
module ppc_core_bat_bus60x #(
  parameter int DISPATCH_WIDTH = 1,
  parameter logic [31:0] RESET_PC = 32'hfff0_0100,
  parameter int DIV_LATENCY = 20,
  // Includes the existing serialized ISYNC/SYNC/EIEIO profile.
  parameter bit ENABLE_SUPERVISOR_EXCEPTIONS = 1'b0,
  parameter bit ENABLE_LIVE_CONTEXT = 1'b0,
  parameter bit ENABLE_EXTERNAL_INTERRUPTS = 1'b0,
  parameter bit ENABLE_TIMERS = 1'b0,
  parameter bit ENABLE_RUNTIME_BAT = 1'b0,
  parameter bit ENABLE_SEGMENT_REGISTERS = 1'b0,
  parameter bit ENABLE_SDR1 = 1'b0,
  parameter bit ENABLE_TGPR = 1'b0,
  parameter bit ENABLE_TLB_MISS_EXCEPTIONS = 1'b0,
  parameter bit ENABLE_PAGE_TRANSLATION = 1'b0,
  parameter bit ENABLE_PAGE_MISS_RESULTS = 1'b0,
  parameter bit ENABLE_PAGE_DATA_EXCEPTIONS = 1'b0,
  parameter bit ENABLE_PAGE_INSTRUCTION_EXCEPTIONS = 1'b0,
  parameter bit ENABLE_TLB_INVALIDATE = 1'b0,
  parameter bit ENABLE_TLB_LOAD = 1'b0
) (
  input  logic clk_i,
  input  logic rst_ni,
  input  logic external_irq_i,
  output logic interrupt_taken_o,
  output logic [31:0] interrupt_pc_o,
  input  logic timer_tick_i,
  input  logic timebase_enable_i,
  output logic decrementer_taken_o,
  output logic [31:0] decrementer_pc_o,
  input  logic bat_write_valid_i,
  output logic bat_write_ready_o,
  input  logic [9:0] bat_write_spr_i,
  input  logic [31:0] bat_write_data_i,
  output logic bat_write_rsp_valid_o,
  input  logic bat_write_rsp_ready_i,
  output logic bat_write_rsp_rejected_o,
  output logic bat_write_rsp_unsupported_o,
  output logic bat_write_rsp_config_error_o,
  output logic bat_write_rsp_overlap_o,
  output logic [3:0] bat_write_rsp_invalid_entry_o,
  input logic tlb_mgmt_req_valid_i,
  output logic tlb_mgmt_req_ready_o,
  input logic [1:0] tlb_mgmt_req_kind_i,
  input logic tlb_mgmt_req_bank_i,
  input logic [31:0] tlb_mgmt_req_ea_i,
  input logic [23:0] tlb_mgmt_req_vsid_i,
  input logic tlb_mgmt_req_pr_i,
  input logic tlb_mgmt_req_way_i,
  input logic [19:0] tlb_mgmt_req_rpn_i,
  input logic tlb_mgmt_req_c_i,
  input logic [3:0] tlb_mgmt_req_wimg_i,
  input logic [1:0] tlb_mgmt_req_pp_i,
  output logic tlb_mgmt_rsp_valid_o,
  input logic tlb_mgmt_rsp_ready_i,
  output logic [1:0] tlb_mgmt_rsp_kind_o,
  output logic tlb_mgmt_rsp_bank_o,
  output logic [31:0] tlb_mgmt_rsp_ea_o,
  output logic tlb_mgmt_rsp_privileged_o,
  output logic tlb_mgmt_rsp_refill_rejected_o,
  output logic tlb_mgmt_rsp_unsupported_o,
  output logic tlb_mgmt_rsp_invalid_input_o,
  output logic tlb_mgmt_idle_o,
  output logic page_fault_o,
  output logic page_miss_o,
  output logic page_protection_o,
  output logic page_no_execute_o,
  output logic page_guarded_o,
  output logic page_direct_store_o,
  output logic page_needs_changed_o,
  output logic page_config_o,
  input  logic start_valid_i,
  output logic start_ready_o,
  input  logic start_ir_i,
  input  logic start_dr_i,
  input  logic start_pr_i,
  output logic running_o,
  output logic context_ir_o,
  output logic context_dr_o,
  output logic context_pr_o,
  output logic retire_valid_o,
  input  logic retire_ready_i,
  output ppc_pkg::retire_packet_t retire_o,
  output logic halted_o,
  input  logic redirect_valid_i,
  input  logic redirect_all_i,
  input  logic redirect_keep_pivot_i,
  input  ppc_pkg::completion_tag_t redirect_pivot_i,
  input  logic [31:0] redirect_target_i,
  output logic redirect_accepted_o,
  output logic translation_fault_o,
  output logic fault_instruction_o,
  output logic fault_write_o,
  output logic [31:0] fault_ea_o,
  output logic fault_miss_o,
  output logic fault_protection_o,
  output logic fault_guarded_o,
  output logic fault_config_o,
  output logic fault_invalid_input_o,
  output logic [3:0] fault_invalid_entry_o,
  output logic pimem_error_o,
  output logic busy_o,
  output logic ifetch_error_o,
  output logic bus_protocol_error_o,
  output logic bus_busy_o,
  output logic        br_n_o,
  input  logic        bg_n_i,
  input  logic        abb_n_i,
  output logic        abb_n_o,
  output logic        abb_oe_o,
  output logic        ts_n_o,
  output logic        ts_oe_o,
  output logic [31:0] a_o,
  output logic [4:0]  tt_o,
  output logic        tbst_n_o,
  output logic [2:0]  tsiz_o,
  output logic [1:0]  tc_o,
  output logic        ci_n_o,
  output logic        wt_n_o,
  output logic        gbl_n_o,
  output logic [1:0]  cse_o,
  output logic        addr_oe_o,
  input  logic        aack_n_i,
  input  logic        artry_n_i,
  input  logic        dbg_n_i,
  input  logic        dbb_n_i,
  output logic        dbb_n_o,
  output logic        dbb_oe_o,
  input  logic [63:0] d_i,
  output logic [63:0] d_o,
  output logic        d_oe_o,
  input  logic        ta_n_i,
  input  logic        drtry_n_i,
  input  logic        tea_n_i
);

  logic core_halted;
  logic imem_req_valid, imem_req_ready;
  logic [31:0] imem_req_addr;
  logic [3:0] unused_pimem_wimg, unused_pdmem_wimg;
  logic imem_rsp_valid, imem_rsp_ready;
  logic [31:0] imem_rsp_insn;
  logic dmem_req_valid, dmem_req_ready, dmem_req_write;
  logic [31:0] dmem_req_addr, dmem_req_wdata;
  logic [3:0] dmem_req_wstrb;
  logic dmem_rsp_valid, dmem_rsp_ready, dmem_rsp_error;
  logic [31:0] dmem_rsp_rdata;

  logic bus_req_valid, bus_req_ready, bus_req_instruction, bus_req_write;
  logic [31:0] bus_req_addr, bus_req_wdata;
  logic [3:0] bus_req_wstrb;
  logic bus_rsp_valid, bus_rsp_ready, bus_rsp_error;
  logic [31:0] bus_rsp_rdata;
  logic router_busy, adapter_busy;

  // BAT, segment and TLB state remain owned by ppc_core_bat. Its physical
  // address outputs alone enter the scalar arbiter. WIMG is deliberately not
  // interpreted by this cache-inhibited 60x transport profile.
  ppc_core_bat #(
    .DISPATCH_WIDTH(DISPATCH_WIDTH),
    .RESET_PC(RESET_PC),
    .DIV_LATENCY(DIV_LATENCY),
    .ENABLE_SUPERVISOR_EXCEPTIONS(ENABLE_SUPERVISOR_EXCEPTIONS),
    .ENABLE_LIVE_CONTEXT(ENABLE_LIVE_CONTEXT),
    .ENABLE_EXTERNAL_INTERRUPTS(ENABLE_EXTERNAL_INTERRUPTS),
    .ENABLE_TIMERS(ENABLE_TIMERS),
    .ENABLE_RUNTIME_BAT(ENABLE_RUNTIME_BAT),
    .ENABLE_SEGMENT_REGISTERS(ENABLE_SEGMENT_REGISTERS),
    .ENABLE_SDR1(ENABLE_SDR1),
    .ENABLE_TGPR(ENABLE_TGPR),
    .ENABLE_TLB_MISS_EXCEPTIONS(ENABLE_TLB_MISS_EXCEPTIONS),
    .ENABLE_PAGE_TRANSLATION(ENABLE_PAGE_TRANSLATION),
    .ENABLE_PAGE_MISS_RESULTS(ENABLE_PAGE_MISS_RESULTS),
    .ENABLE_PAGE_DATA_EXCEPTIONS(ENABLE_PAGE_DATA_EXCEPTIONS),
    .ENABLE_PAGE_INSTRUCTION_EXCEPTIONS(ENABLE_PAGE_INSTRUCTION_EXCEPTIONS),
    .ENABLE_TLB_INVALIDATE(ENABLE_TLB_INVALIDATE),
    .ENABLE_TLB_LOAD(ENABLE_TLB_LOAD)
  ) translated_core (
    .clk_i,
    .rst_ni,
    .external_irq_i,
    .interrupt_taken_o,
    .interrupt_pc_o,
    .timer_tick_i,
    .timebase_enable_i,
    .decrementer_taken_o,
    .decrementer_pc_o,
    .bat_write_valid_i,
    .bat_write_ready_o,
    .bat_write_spr_i,
    .bat_write_data_i,
    .bat_write_rsp_valid_o,
    .bat_write_rsp_ready_i,
    .bat_write_rsp_rejected_o,
    .bat_write_rsp_unsupported_o,
    .bat_write_rsp_config_error_o,
    .bat_write_rsp_overlap_o,
    .bat_write_rsp_invalid_entry_o,
    .tlb_mgmt_req_valid_i,
    .tlb_mgmt_req_ready_o,
    .tlb_mgmt_req_kind_i,
    .tlb_mgmt_req_bank_i,
    .tlb_mgmt_req_ea_i,
    .tlb_mgmt_req_vsid_i,
    .tlb_mgmt_req_pr_i,
    .tlb_mgmt_req_way_i,
    .tlb_mgmt_req_rpn_i,
    .tlb_mgmt_req_c_i,
    .tlb_mgmt_req_wimg_i,
    .tlb_mgmt_req_pp_i,
    .tlb_mgmt_rsp_valid_o,
    .tlb_mgmt_rsp_ready_i,
    .tlb_mgmt_rsp_kind_o,
    .tlb_mgmt_rsp_bank_o,
    .tlb_mgmt_rsp_ea_o,
    .tlb_mgmt_rsp_privileged_o,
    .tlb_mgmt_rsp_refill_rejected_o,
    .tlb_mgmt_rsp_unsupported_o,
    .tlb_mgmt_rsp_invalid_input_o,
    .tlb_mgmt_idle_o,
    .page_fault_o,
    .page_miss_o,
    .page_protection_o,
    .page_no_execute_o,
    .page_guarded_o,
    .page_direct_store_o,
    .page_needs_changed_o,
    .page_config_o,
    .start_valid_i,
    .start_ready_o,
    .start_ir_i,
    .start_dr_i,
    .start_pr_i,
    .running_o,
    .context_ir_o,
    .context_dr_o,
    .context_pr_o,
    .pimem_req_valid_o(imem_req_valid),
    .pimem_req_ready_i(imem_req_ready),
    .pimem_req_addr_o(imem_req_addr),
    .pimem_req_wimg_o(unused_pimem_wimg),
    .pimem_rsp_valid_i(imem_rsp_valid),
    .pimem_rsp_ready_o(imem_rsp_ready),
    .pimem_rsp_insn_i(imem_rsp_insn),
    .pimem_rsp_error_i(1'b0),
    .pdmem_req_valid_o(dmem_req_valid),
    .pdmem_req_ready_i(dmem_req_ready),
    .pdmem_req_write_o(dmem_req_write),
    .pdmem_req_addr_o(dmem_req_addr),
    .pdmem_req_wdata_o(dmem_req_wdata),
    .pdmem_req_wstrb_o(dmem_req_wstrb),
    .pdmem_req_wimg_o(unused_pdmem_wimg),
    .pdmem_rsp_valid_i(dmem_rsp_valid),
    .pdmem_rsp_ready_o(dmem_rsp_ready),
    .pdmem_rsp_rdata_i(dmem_rsp_rdata),
    .pdmem_rsp_error_i(dmem_rsp_error),
    .retire_valid_o,
    .retire_ready_i,
    .retire_o,
    .halted_o(core_halted),
    .redirect_valid_i,
    .redirect_all_i,
    .redirect_keep_pivot_i,
    .redirect_pivot_i,
    .redirect_target_i,
    .redirect_accepted_o,
    .translation_fault_o,
    .fault_instruction_o,
    .fault_write_o,
    .fault_ea_o,
    .fault_miss_o,
    .fault_protection_o,
    .fault_guarded_o,
    .fault_config_o,
    .fault_invalid_input_o,
    .fault_invalid_entry_o,
    .pimem_error_o,
    .busy_o
  );
  ppc_bus60x_arbiter transport_router (
    .clk_i, .rst_ni,
    .imem_req_valid_i(imem_req_valid),
    .imem_req_ready_o(imem_req_ready),
    .imem_req_addr_i(imem_req_addr),
    .imem_rsp_valid_o(imem_rsp_valid),
    .imem_rsp_ready_i(imem_rsp_ready),
    .imem_rsp_insn_o(imem_rsp_insn),
    .dmem_req_valid_i(dmem_req_valid),
    .dmem_req_ready_o(dmem_req_ready),
    .dmem_req_write_i(dmem_req_write),
    .dmem_req_addr_i(dmem_req_addr),
    .dmem_req_wdata_i(dmem_req_wdata),
    .dmem_req_wstrb_i(dmem_req_wstrb),
    .dmem_rsp_valid_o(dmem_rsp_valid),
    .dmem_rsp_ready_i(dmem_rsp_ready),
    .dmem_rsp_rdata_o(dmem_rsp_rdata),
    .dmem_rsp_error_o(dmem_rsp_error),
    .bus_req_valid_o(bus_req_valid),
    .bus_req_ready_i(bus_req_ready),
    .bus_req_instruction_o(bus_req_instruction),
    .bus_req_write_o(bus_req_write),
    .bus_req_addr_o(bus_req_addr),
    .bus_req_wdata_o(bus_req_wdata),
    .bus_req_wstrb_o(bus_req_wstrb),
    .bus_rsp_valid_i(bus_rsp_valid),
    .bus_rsp_ready_o(bus_rsp_ready),
    .bus_rsp_rdata_i(bus_rsp_rdata),
    .bus_rsp_error_i(bus_rsp_error),
    .ifetch_error_o, .busy_o(router_busy)
  );

  ppc_bus60x bus (
    .clk_i, .rst_ni,
    .req_valid_i(bus_req_valid), .req_ready_o(bus_req_ready),
    .req_instruction_i(bus_req_instruction),
    .req_write_i(bus_req_write), .req_addr_i(bus_req_addr),
    .req_wdata_i(bus_req_wdata), .req_wstrb_i(bus_req_wstrb),
    .rsp_valid_o(bus_rsp_valid), .rsp_ready_i(bus_rsp_ready),
    .rsp_rdata_o(bus_rsp_rdata), .rsp_error_o(bus_rsp_error),
    .busy_o(adapter_busy), .protocol_error_o(bus_protocol_error_o),
    .br_n_o, .bg_n_i, .abb_n_i, .abb_n_o, .abb_oe_o,
    .ts_n_o, .ts_oe_o, .a_o, .tt_o, .tbst_n_o, .tsiz_o,
    .tc_o, .ci_n_o, .wt_n_o, .gbl_n_o, .cse_o, .addr_oe_o,
    .aack_n_i, .artry_n_i, .dbg_n_i, .dbb_n_i,
    .dbb_n_o, .dbb_oe_o, .d_i, .d_o, .d_oe_o,
    .ta_n_i, .drtry_n_i, .tea_n_i
  );

  // As in the physical scalar wrapper, instruction TEA is a sticky terminal
  // transport stop. The arbiter consumes it without presenting an instruction
  // word or a typed page fault to the translation router.
  assign halted_o = core_halted || ifetch_error_o;
  assign bus_busy_o = router_busy || adapter_busy;
endmodule
