#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Kevin Dedon
"""Writes the struct offsets and sizes the Amiga Quake PowerPC sources
include (quakedefPPC.i) from the command file the original generator reads
(quakeasmheaders.gen), measured with the cross-compiler on the engine's own
headers: the compiler prints each value into its assembly output, so
nothing runs on the host.

Command file: '#h "header"' includes a header, '#s type PREFIX' starts a
structure, 'member NAME' writes PREFIX_NAME = offsetof(type, member), '#l'
writes PREFIX_SIZEOF and '#e' PREFIX_SIZEOF_EXP (log2 of the size).

The structures that the engine defines in d_polyse.c, not in a header, come
from compiling that file into the probe.

Usage: asmoffsets.py commands.gen engine-dir out.i -- cc flags..."""
import os
import re
import subprocess
import sys
import tempfile


def main(argv):
    if '--' not in argv or argv.index('--') != 3:
        sys.exit(__doc__)
    gen, engine, out = argv[:3]
    cc = argv[4:]
    probe = ['#include <stddef.h>', f'#include "{os.path.abspath(os.path.join(engine, "d_polyse.c"))}"',
             '#define V(name, v) __asm__ volatile("\\n@@ " name " %0" :: "i"((int)(v)))',
             'void quake_asm_offsets(void);', 'void quake_asm_offsets(void)', '{']
    struct = prefix = None
    for line in open(gen, encoding='latin-1').read().splitlines():
        if line.startswith('#'):
            cmd = line[1:2].lower()
            if cmd == 's':
                fields = line[3:].split()
                struct, prefix = fields[0], (fields[1] + '_' if len(fields) > 1 else '')
            elif cmd == 'l':
                probe.append(f'  V("{prefix}SIZEOF", sizeof({struct}));')
            elif cmd == 'e':
                probe.append(f'  V("{prefix}SIZEOF_EXP", __builtin_ctz(sizeof({struct})));')
                probe.append(f'  _Static_assert((sizeof({struct}) & (sizeof({struct}) - 1)) == 0, '
                             f'"{struct} size is not a power of two");')
        elif len(line.strip()) > 3 and struct:
            member, name = line.split()[:2]
            probe.append(f'  V("{prefix}{name}", offsetof({struct}, {member}));')
    probe.append('}')
    with tempfile.TemporaryDirectory() as tmp:
        src = os.path.join(tmp, 'probe.c')
        open(src, 'w').write('\n'.join(probe) + '\n')
        asm = subprocess.run(cc + ['-S', '-o', '-', src], check=True, capture_output=True,
                             text=True).stdout
    values = re.findall(r'^\s*@@ (\w+) (-?\d+)\s*$', asm, re.M)
    expected = sum(1 for p in probe if p.startswith('  V('))
    if len(values) != expected:
        sys.exit(f'asmoffsets: {len(values)} values from the compiler, {expected} expected')
    with open(out, 'w') as f:
        f.write('# Generated by asmoffsets.py from quakeasmheaders.gen.\n')
        for name, value in values:
            f.write(f'.set\t{name},{value}\n')


if __name__ == '__main__':
    main(sys.argv[1:])
