../../rtl/ppc_pkg.sv
../../rtl/fpu/ppc_fpu_pkg.sv
../../rtl/ppc_fifo.sv
../../rtl/ppc_iq.sv
../../rtl/ppc_fetch.sv
../../rtl/ppc_decode.sv
../../rtl/ppc_dispatch.sv
../../rtl/ppc_divider.sv
../../rtl/ppc_iu.sv
../../rtl/ppc_regfile_gpr.sv
../../rtl/ppc_rename.sv
../../rtl/ppc_completion.sv
../../rtl/ppc_flags.sv
../../rtl/ppc_exception_state.sv
../../rtl/ppc_timer.sv
../../rtl/ppc_miss_derive.sv
../../rtl/ppc_watchdog.sv
../../rtl/ppc_special.sv
../../rtl/ppc_lsu_sequence.sv
../../rtl/ppc_core.sv
../../rtl/ppc_bat_translate.sv
../../rtl/ppc_bat_service.sv
../../rtl/ppc_segment_registers.sv
../../rtl/ppc_tlb_ram.sv
../../rtl/ppc_tlb_service.sv
../../rtl/ppc_micro_tlb.sv
../../rtl/ppc_bat_memory_router.sv
../../rtl/ppc_core_bat.sv
../../rtl/ppc_bus60x.sv
../../rtl/ppc_bus60x_arbiter.sv
../../rtl/ppc_bus60x_line_read.sv
../../rtl/ppc_ram_sdp.sv
../../rtl/ppc_ram_lut.sv
../../rtl/ppc_icache.sv
../../rtl/ppc_bus60x_master_select.sv
../../rtl/ppc_bus60x_two_master.sv
../../rtl/ppc_icache_managed.sv
../../rtl/ppc_dcache_pkg.sv
../../rtl/ppc_ram_sdp_be.sv
../../rtl/ppc_dcache.sv
../../rtl/ppc_dcache_slot.sv
../../rtl/ppc_bus60x_cache_master.sv
../../rtl/ppc_bus60x_snoop.sv
../../rtl/ppc_bus60x_direct_store.sv
../../rtl/ppc_biu.sv
../../rtl/ppc_core_bat_cached_bus60x.sv
../../rtl/ppc602_bus.sv
../../rtl/ppc602.sv
ppc602_measure.sv
