// Live BAT + EXT + TB/DEC measurement. Every wrapper port remains observable.
// No cache/60x composition, fixed memory responder or folded trace.
module ppc_timer_bat_measure (
  input  logic clk_i,
  input  logic rst_ni,
  input  logic external_irq_i,
  output logic interrupt_taken_o,
  output logic [31:0] interrupt_pc_o,
  input  logic timer_tick_i,
  input  logic timebase_enable_i,
  output logic decrementer_taken_o,
  output logic [31:0] decrementer_pc_o,
  input  logic bat_write_valid_i,
  output logic bat_write_ready_o,
  input  logic [9:0] bat_write_spr_i,
  input  logic [31:0] bat_write_data_i,
  output logic bat_write_rsp_valid_o,
  input  logic bat_write_rsp_ready_i,
  output logic bat_write_rsp_rejected_o,
  output logic bat_write_rsp_unsupported_o,
  output logic bat_write_rsp_config_error_o,
  output logic bat_write_rsp_overlap_o,
  output logic [3:0] bat_write_rsp_invalid_entry_o,
  input  logic start_valid_i,
  output logic start_ready_o,
  input  logic start_ir_i,
  input  logic start_dr_i,
  input  logic start_pr_i,
  output logic running_o,
  output logic context_ir_o,
  output logic context_dr_o,
  output logic context_pr_o,
  output logic pimem_req_valid_o,
  input  logic pimem_req_ready_i,
  output logic [31:0] pimem_req_addr_o,
  output logic [3:0] pimem_req_wimg_o,
  input  logic pimem_rsp_valid_i,
  output logic pimem_rsp_ready_o,
  input  logic [31:0] pimem_rsp_insn_i,
  input  logic pimem_rsp_error_i,
  output logic pdmem_req_valid_o,
  input  logic pdmem_req_ready_i,
  output logic pdmem_req_write_o,
  output logic [31:0] pdmem_req_addr_o,
  output logic [31:0] pdmem_req_wdata_o,
  output logic [3:0] pdmem_req_wstrb_o,
  output logic [3:0] pdmem_req_wimg_o,
  input  logic pdmem_rsp_valid_i,
  output logic pdmem_rsp_ready_o,
  input  logic [31:0] pdmem_rsp_rdata_i,
  input  logic pdmem_rsp_error_i,
  output logic retire_valid_o,
  input  logic retire_ready_i,
  output ppc_pkg::retire_packet_t retire_o,
  output logic halted_o,
  input  logic redirect_valid_i,
  input  logic redirect_all_i,
  input  logic redirect_keep_pivot_i,
  input  ppc_pkg::completion_tag_t redirect_pivot_i,
  input  logic [31:0] redirect_target_i,
  output logic redirect_accepted_o,
  output logic translation_fault_o,
  output logic fault_instruction_o,
  output logic fault_write_o,
  output logic [31:0] fault_ea_o,
  output logic fault_miss_o,
  output logic fault_protection_o,
  output logic fault_guarded_o,
  output logic fault_config_o,
  output logic fault_invalid_input_o,
  output logic [3:0] fault_invalid_entry_o,
  output logic pimem_error_o,
  output logic busy_o
);
  logic [49:0] unused_page;
  ppc_core_bat #(
    .ENABLE_SUPERVISOR_EXCEPTIONS(1'b1),
    .ENABLE_LIVE_CONTEXT(1'b1),
    .ENABLE_EXTERNAL_INTERRUPTS(1'b1),
    .ENABLE_TIMERS(1'b1)
  ) dut (
    .tlb_mgmt_req_valid_i(1'b0),
    .tlb_mgmt_req_ready_o(unused_page[0]),
    .tlb_mgmt_req_kind_i(2'b0),
    .tlb_mgmt_req_bank_i(1'b0),
    .tlb_mgmt_req_ea_i(32'b0),
    .tlb_mgmt_req_vsid_i(24'b0),
    .tlb_mgmt_req_pr_i(1'b0),
    .tlb_mgmt_req_way_i(1'b0),
    .tlb_mgmt_req_rpn_i(20'b0),
    .tlb_mgmt_req_c_i(1'b0),
    .tlb_mgmt_req_wimg_i(4'b0),
    .tlb_mgmt_req_pp_i(2'b0),
    .tlb_mgmt_rsp_valid_o(unused_page[1]),
    .tlb_mgmt_rsp_ready_i(1'b0),
    .tlb_mgmt_rsp_kind_o(unused_page[3:2]),
    .tlb_mgmt_rsp_bank_o(unused_page[4]),
    .tlb_mgmt_rsp_ea_o(unused_page[36:5]),
    .tlb_mgmt_rsp_privileged_o(unused_page[37]),
    .tlb_mgmt_rsp_refill_rejected_o(unused_page[38]),
    .tlb_mgmt_rsp_unsupported_o(unused_page[39]),
    .tlb_mgmt_rsp_invalid_input_o(unused_page[40]),
    .tlb_mgmt_idle_o(unused_page[41]),
    .page_fault_o(unused_page[42]),
    .page_miss_o(unused_page[43]),
    .page_protection_o(unused_page[44]),
    .page_no_execute_o(unused_page[45]),
    .page_guarded_o(unused_page[46]),
    .page_direct_store_o(unused_page[47]),
    .page_needs_changed_o(unused_page[48]),
    .page_config_o(unused_page[49]),
    .*
  );
endmodule
