// Translated cached 60x MVP profile: every wrapper port remains a virtual port.
// Bus data returns are runtime inputs, so decode is not specialized to one program.
// No behavioral responder, constant memory inputs or folded retirement digest.
module ppc_translated_measure (
  input logic clk_i,
  input logic rst_ni,
  input logic external_irq_i,
  output logic interrupt_taken_o,
  output logic [31:0] interrupt_pc_o,
  input logic timer_tick_i,
  input logic timebase_enable_i,
  output logic decrementer_taken_o,
  output logic [31:0] decrementer_pc_o,
  input logic bat_write_valid_i,
  output logic bat_write_ready_o,
  input logic [9:0] bat_write_spr_i,
  input logic [31:0] bat_write_data_i,
  output logic bat_write_rsp_valid_o,
  input logic bat_write_rsp_ready_i,
  output logic bat_write_rsp_rejected_o,
  output logic bat_write_rsp_unsupported_o,
  output logic bat_write_rsp_config_error_o,
  output logic bat_write_rsp_overlap_o,
  output logic [3:0] bat_write_rsp_invalid_entry_o,
  input logic tlb_mgmt_req_valid_i,
  output logic tlb_mgmt_req_ready_o,
  input logic [1:0] tlb_mgmt_req_kind_i,
  input logic tlb_mgmt_req_bank_i,
  input logic [31:0] tlb_mgmt_req_ea_i,
  input logic [23:0] tlb_mgmt_req_vsid_i,
  input logic tlb_mgmt_req_pr_i,
  input logic tlb_mgmt_req_way_i,
  input logic [19:0] tlb_mgmt_req_rpn_i,
  input logic tlb_mgmt_req_c_i,
  input logic [3:0] tlb_mgmt_req_wimg_i,
  input logic [1:0] tlb_mgmt_req_pp_i,
  output logic tlb_mgmt_rsp_valid_o,
  input logic tlb_mgmt_rsp_ready_i,
  output logic [1:0] tlb_mgmt_rsp_kind_o,
  output logic tlb_mgmt_rsp_bank_o,
  output logic [31:0] tlb_mgmt_rsp_ea_o,
  output logic tlb_mgmt_rsp_privileged_o,
  output logic tlb_mgmt_rsp_refill_rejected_o,
  output logic tlb_mgmt_rsp_unsupported_o,
  output logic tlb_mgmt_rsp_invalid_input_o,
  output logic tlb_mgmt_idle_o,
  output logic page_fault_o,
  output logic page_miss_o,
  output logic page_protection_o,
  output logic page_no_execute_o,
  output logic page_guarded_o,
  output logic page_direct_store_o,
  output logic page_needs_changed_o,
  output logic page_config_o,
  input logic start_valid_i,
  output logic start_ready_o,
  input logic start_ir_i,
  input logic start_dr_i,
  input logic start_pr_i,
  output logic running_o,
  output logic context_ir_o,
  output logic context_dr_o,
  output logic context_pr_o,
  output logic retire_valid_o,
  input logic retire_ready_i,
  output ppc_pkg::retire_packet_t retire_o,
  output logic halted_o,
  input logic redirect_valid_i,
  input logic redirect_all_i,
  input logic redirect_keep_pivot_i,
  input ppc_pkg::completion_tag_t redirect_pivot_i,
  input logic [31:0] redirect_target_i,
  output logic redirect_accepted_o,
  output logic translation_fault_o,
  output logic fault_instruction_o,
  output logic fault_write_o,
  output logic [31:0] fault_ea_o,
  output logic fault_miss_o,
  output logic fault_protection_o,
  output logic fault_guarded_o,
  output logic fault_config_o,
  output logic fault_invalid_input_o,
  output logic [3:0] fault_invalid_entry_o,
  output logic pimem_error_o,
  output logic busy_o,
  output logic ifetch_error_o,
  output logic bus_protocol_error_o,
  output logic bus_busy_o,
  output logic icache_hit_o,
  output logic icache_miss_o,
  output logic icache_busy_o,
  input logic maintenance_valid_i,
  output logic maintenance_ready_o,
  input logic maintenance_invalidate_i,
  input logic maintenance_cache_enable_i,
  output logic maintenance_done_valid_o,
  input logic maintenance_done_ready_i,
  output logic cache_enabled_o,
  output logic maintenance_busy_o,
  output logic br_n_o,
  input logic bg_n_i,
  input logic abb_n_i,
  output logic abb_n_o,
  output logic abb_oe_o,
  output logic ts_n_o,
  output logic ts_oe_o,
  output logic [31:0] a_o,
  output logic [4:0] tt_o,
  output logic tbst_n_o,
  output logic [2:0] tsiz_o,
  output logic [1:0] tc_o,
  output logic ci_n_o,
  output logic wt_n_o,
  output logic gbl_n_o,
  output logic [1:0] cse_o,
  output logic addr_oe_o,
  input logic aack_n_i,
  input logic artry_n_i,
  input logic dbg_n_i,
  input logic dbb_n_i,
  output logic dbb_n_o,
  output logic dbb_oe_o,
  input logic [63:0] d_i,
  output logic [63:0] d_o,
  output logic d_oe_o,
  input logic ta_n_i,
  input logic drtry_n_i,
  input logic tea_n_i
);
  // The core resets synchronously; this chain registers the external reset so
  // its arrival no longer reaches reset logic directly.
  logic [1:0] rst_sync_q;
  always_ff @(posedge clk_i) rst_sync_q <= {rst_sync_q[0], rst_ni};

  ppc_core_bat_cached_bus60x #(
    .RESET_CACHE_ENABLE(1'b0),
    .ENABLE_SUPERVISOR_EXCEPTIONS(1'b1),
    .ENABLE_LIVE_CONTEXT(1'b1),
    .ENABLE_EXTERNAL_INTERRUPTS(1'b1),
    .ENABLE_TIMERS(1'b1),
    .ENABLE_RUNTIME_BAT(1'b1),
    .ENABLE_SEGMENT_REGISTERS(1'b1),
    .ENABLE_SDR1(1'b1),
    .ENABLE_TGPR(1'b1),
    .ENABLE_TLB_MISS_EXCEPTIONS(1'b1),
    .ENABLE_PAGE_TRANSLATION(1'b1),
    .ENABLE_PAGE_MISS_RESULTS(1'b1),
    .ENABLE_PAGE_DATA_EXCEPTIONS(1'b1),
    .ENABLE_PAGE_INSTRUCTION_EXCEPTIONS(1'b1),
    .ENABLE_TLB_INVALIDATE(1'b1),
    .ENABLE_TLB_LOAD(1'b1),
    .ENABLE_TEST_REDIRECT(1'b0)
  ) dut (.rst_ni(rst_sync_q[1]), .*);
endmodule
