#!/bin/sh
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (c) 2026 Kevin Dedon
# tools/verilate with the pipelined load/store unit on in every top, for
# VERILATOR and VERILATOR_TOOL.
exec "$(dirname "$0")/verilate" +define+PPC_LSU_PIPE=1 "$@"
