#!/usr/bin/env bash
# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Kevin Dedon
# Builds the MiSTer core: fetches the framework, builds the firmware image in
# the pinned cross-compiler container, generates files.qip and compiles in the
# pinned Quartus image. Prints resources, the worst slack of every clock at
# every corner, and the .rbf path; fails on a negative slack. With --clean,
# only the .rbf and the fit and timing summaries are kept afterwards. With
# --native, the 320 x 240 framebuffer is on chip and leaves as native video
# instead of the 1920 x 1080 DDR3 framebuffer shown by the scaler.
set -euo pipefail
clean=0
native=0
for arg in "$@"; do
  case "${arg}" in
    --clean) clean=1 ;;
    --native) native=1 ;;
    *) echo "usage: $0 [--clean] [--native]" >&2; exit 2 ;;
  esac
done
here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd -- "${here}/.." && pwd)"
image="${QUARTUS_IMAGE:-theypsilon/quartus-lite-c5@sha256:f638634df509786bc7507dbcb45673acd6adf32e5278c7b4e64ce67ae8ac2c70}"
short="$(git -C "${repo}" rev-parse --short HEAD)"
if [[ -n "$(git -C "${repo}" status --porcelain -- rtl mister toolchain/demo)" ]]; then
  short="${short}+"
fi

"${here}/fetch-framework.sh"
"${repo}/toolchain/demo/fetch-benchmarks.sh"
"${repo}/toolchain/build-in-container.sh" -f demo/Makefile mister "GIT_SHORT=${short}"
mkdir -p "${here}/firmware"
cp "${repo}/toolchain/build/demo/mister.hex" "${here}/firmware/mister.hex"
# Depth is RAM_BYTES / 8 of ppc603e_mister.
python3 "${here}/hex2mif.py" "${here}/firmware/mister.hex" 16384 "${here}/firmware/mister.mif"

{
  echo "# Generated by build.sh from rtl/chip_files.f and rtl/soc/files.f."
  cat "${repo}/rtl/chip_files.f" "${repo}/rtl/soc/files.f" |
    sed 's|^|set_global_assignment -name SYSTEMVERILOG_FILE |'
  echo "set_global_assignment -name SYSTEMVERILOG_FILE rtl/ppc603e_mister.sv"
  echo "set_global_assignment -name SYSTEMVERILOG_FILE ppc603e.sv"
  echo "set_global_assignment -name SDC_FILE ppc603e.sdc"
} > "${here}/files.qip"

rm -rf "${here}/output_files" "${here}/build_id.v"
# Quartus writes every sourced assignment back into the project file.
cp "${here}/ppc603e.qsf" "${here}/ppc603e.qsf.keep"
if [[ "${native}" == 1 ]]; then
  sed -i '/VERILOG_MACRO "MISTER_FB/d' "${here}/ppc603e.qsf"
fi
status=0
# One Quartus build at a time on a shared machine.
flock /tmp/ppc603e-quartus.lock docker run --rm --network none --user "$(id -u):$(id -g)" --volume "${repo}:/work" \
  --workdir /work/mister "${image}" \
  /opt/intelFPGA_lite/quartus/bin/quartus_sh --flow compile ppc603e -c ppc603e \
  > "${here}/output_files.log" 2>&1 || status=$?
mv "${here}/ppc603e.qsf.keep" "${here}/ppc603e.qsf"

out="${here}/output_files"
# A RAM whose init file was not read would boot from zeros.
if grep -q "Critical Warning (127002)" "${here}/output_files.log"; then
  echo "firmware: memory init file not read" >&2
  status=1
fi
if [[ -f "${out}/ppc603e.fit.rpt" ]]; then
  # The program RAM's row of the fitter RAM summary names its init file.
  if ! grep -m1 "mister.mif" "${out}/ppc603e.fit.rpt" | sed "s/ ; M10K_X.*//" | tr -s " "; then
    echo "firmware: program RAM has no init file" >&2
    status=1
  fi
fi
if [[ -f "${out}/ppc603e.fit.summary" ]]; then
  grep -E "Logic utilization|Total registers|Total block memory bits|Total RAM Blocks|Total DSP Blocks|Total PLLs" \
    "${out}/ppc603e.fit.summary" || true
fi
if [[ -f "${out}/ppc603e.sta.summary" ]]; then
  # One line per corner, analysis and clock: worst slack.
  awk -F' : ' '/^Type/ {type=$2} /^Slack/ {print type ": " $2}' "${out}/ppc603e.sta.summary"
  if awk -F' : ' '/^Slack/ && $2 < 0 {bad=1} END {exit !bad}' "${out}/ppc603e.sta.summary"; then
    echo "timing: negative slack" >&2
    status=1
  fi
fi
if [[ -f "${out}/ppc603e.rbf" ]]; then
  echo "rbf: ${out}/ppc603e.rbf (${short}, $([[ "${native}" == 1 ]] && echo "native video" || echo "1920x1080 DDR3 framebuffer"))"
fi
echo "quartus exit status ${status}"
if [[ "${clean}" == 1 ]]; then
  rm -rf "${here}/db" "${here}/incremental_db" "${here}"/*.qws
  find "${out}" -type f ! -name '*.rbf' ! -name '*.summary' -delete 2>/dev/null || true
fi
exit "${status}"
